# Generated by Django 5.0.1 on 2024-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listings_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='picture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
